# Generated by Django 3.2.5 on 2021-07-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('titular', models.CharField(max_length=150)),
                ('conta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
