# Generated by Django 3.2.5 on 2021-07-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
